### ISSUE TITLE
Attn.forward comment

### ISSUE THREAD

**Issue by uenewsar** [AuCson/PyTorch-Batch-Attention-Seq2seq#1]
Thank you for your very helpful code.
Comments in Attn.forward method seem not correct. 
1. hidden argument's shape is not (layers*directions,B,H) but (B,H).
2. attention energies' shape is not (B,T) but (B,1,T).

**Comment by AuCson** [comment]
Hi:
Thanks for your reminding. I will fix it as soon as possible.
