### ISSUE TITLE
Decoder, last_hidden: Wrong dimensions

### ISSUE THREAD

**Issue by x-dennis** [AuCson/PyTorch-Batch-Attention-Seq2seq#2]
Thanks for sharing your code which is pretty clear and not as bloated as the other repositories showcasing sequence-to-sequence networks with attention.

Unfortunately the dimensions do not add up at one point:

The encoder's GRU layer outputs its hidden states in the shape of [layers*direction,B,H] or in my case  [2,B,H] (one layer, bidirectional). 

On the other hand the decoder's GRU actually expects the hidden state to be of shape [layers,B,H] which means [1,B,H] for me.

I have simply concatenated the two layers with the hidden state in the encoder like this:

```
hidden = hidden[0] + hidden[1]
hidden = hidden.unsqueeze(0)
```

But I am wondering if this is a valid approach. I would be thankful for suggestions on how to deal with it ideally.

**Comment by AuCson** [comment]
Hi:
Thanks for your question. According to some papers(where detailed illustration on their seq2seq architectures is provided), some authors use the last hidden state of the forward pass of bi-directional encoder as the decoder initial hidden state, while some prefers that of the backward pass.
However it seems there is no definite conclusion on which one(forward, backward, or sum?) should be used. If summing two hidden states works (or even works better) for you, I suppose it is a valid approach.
