### ISSUE TITLE
Attention weights problem

### ISSUE THREAD

**Issue by parajain** [AuCson/PyTorch-Batch-Attention-Seq2seq#3]
Hi,

Thanks for the code :)
I tried the implementation to test it on a translation task, but attention weights after 2-3 epochs stick to only one input word.
Have you tested it in any known task? Will it be possible to share some code which I can try and understand?

Thanks,
Parag

**Comment by parajain** [comment]
**Epoch 2** 
![epoch_2_5](https://user-images.githubusercontent.com/8446082/35731864-52b7b020-083d-11e8-980a-ae2b8ac61bfb.jpg)
**Epoch 4**
![epoch_4_5](https://user-images.githubusercontent.com/8446082/35731867-54280cc0-083d-11e8-84bc-724465c3347b.jpg)

**Comment by SivilTaram** [comment]
Hi @pj-parag I have encountered the same problem. I rechecked the code and the solution as the author commited on Feb in line 64:
`        
energy = F.tanh(self.attn(torch.cat([hidden, encoder_outputs], 2))) # [B*T*2H]->[B*T*H]
`

It seems a lack of non-linear activation before the author fixed it on Feb. 8 :)
