### ISSUE TITLE
Attention Class: Explanation of variable `v` in `_score` method

### ISSUE THREAD

**Issue by x-dennis** [AuCson/PyTorch-Batch-Attention-Seq2seq#5]
I can't wrap my head around these lines in the `Attn` Class:

```
v = self.v.repeat(encoder_outputs.data.shape[0],1).unsqueeze(1) #[B*1*H]
energy = torch.bmm(v,energy) # [B*1*T]
```

What is the purpose of `v` and what does it refer to in the paper? Why is it necessary to mulitply the 'energies' by it? 

A quick explanation would be highly appreciated!

**Comment by AuCson** [comment]
Hi:
Please see the formula below, which is included in the appendix in original paper: https://arxiv.org/pdf/1409.0473.pdf]:

<img src="https://pic1.zhimg.com/80/v2-9cff20aefe3703e00c9f5b9e8e17a81c_hd.jpg">

After the non-linear transformation(tanh(W..+U..)) of the concatenation of h_encoder_j and h_decoder_i-1, we get a vector representation(that is, "attention energy"), which is of hidden_size dimension. However, we would like to assign a "scalar score e_ij" between h_encoder_j and h_decoder_i-1, so we can compute a dot product between a vector v and the attention energy. V is also a trainable parameter.

**Comment by x-dennis** [comment]
As before your timely response is great! I did not notice the appendix - shame on me. Thank you for your help.

My followup question is out of the scope of your implementation but do you have any idea why **any** vector representation of the "attention energies" gets multiplied by the **same** vector `v`? Does this not defeat the purpose of the attention mechanism which is to identify the energies/weights individually depending on the given state and output? This way the energy vectors are influenced by `v` which is independent of the states and outputs and generalized over the training set as far as I understand it. The only intuition that pops up in my mind is that `v` is learned as a general distribution of weights which are emphasized or inhibited based on the energy vectors. But I might be wrong here.

If you have an explanation for this and a few more minutes to spare, I would be glad to get your answer!

**Comment by AuCson** [comment]
As I think the parameter `v` has no difference from other model parameters like `W` or `U` - `v` is an [h\*1] matrix, while `W` and `U` are [h\*h] matrix.  Neither of them have a input dimension for T(time step), so they are all "independent of the states and outputs" with regards to their **absolute** position in a sequence.

However state and hidden vectors generated from different time steps of an RNN are different. Therefore, the `e_ij` will differ, although they are computed with the same model parameter "W,U and v". `e_ij` can be regarded as the "interactive score" between the i-th token in encoder and j-th token in decoder. I think it is how attention works.

Besides, there was a mistake in my first answer. "attention energy" does not refer to "tanh(W..+U..)" but it refers to "e_ij". Sorry for that.
