### ISSUE TITLE
The shape of the hidden vector is not match with encoder_outputs

### ISSUE THREAD

**Issue by silverriver** [AuCson/PyTorch-Batch-Attention-Seq2seq#7]
https://github.com/AuCson/PyTorch-Batch-Attention-Seq2seq/blob/8334155c85dd9ff41218273d00e0e29690f0bfd6/attentionRNN.py#L58

The size of hidden should be (layers*directions,B,H).
That means H will be size of (B, layer * directions * T, H)
Which will cause error when calcuating the weights.

**Comment by AuCson** [comment]
Yes, you are right. However, this code only meant to tackle single layer cases.
I will improve this recently. Thanks!
