### ISSUE TITLE
Problem with dimensions:

### ISSUE THREAD

**Issue by ankitvad** [AuCson/PyTorch-Batch-Attention-Seq2seq#8]
Doesn't doing this cause a problem in the dimension ?
https://github.com/AuCson/PyTorch-Batch-Attention-Seq2seq/blob/8334155c85dd9ff41218273d00e0e29690f0bfd6/attentionRNN.py#L120

Since, out = nn.Linear(hidden * 2, output_size)
this should be out = nn.Linear(hidden, output_size)
right ?

**Comment by AuCson** [comment]
fixed. Thanks!
